spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hellokitty_micromarket?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
